chains:
  gaia-testnet:
    key: openbitlab
    chain-id: GAIA
    rpc-addr: http://stride.stake-take.com:46657
    grpc-addr: http://stride.stake-take.com:9490
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: openbitlab
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://stride.stake-take.com:26657
    grpc-addr: http://stride.stake-take.com:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
